# This playbook downloads DSE in this site.
# Configure basics
- hosts: all
  remote_user: root
  become: true
  roles:
  - common


# Download DSE cluster nodes
- hosts: seeds,non_seeds
  remote_user: root
  serial: 5
  become: true
  roles:
  - db-setup
